create table users
(
    id           bigint generated by default as identity (start with 0) primary key,
    username     varchar_ignorecase(50)  not null unique,
    password     varchar_ignorecase(500) not null,
    firstname    varchar_ignorecase(100) not null,
    lastname     varchar_ignorecase(100) not null,
    email        varchar_ignorecase(250) not null unique,
    enabled      boolean                 not null,
    accExpired   boolean                 not null,
    credsExpired boolean                 not null,
    accLocked    boolean                 not null
);
//create table authorities
//(
//    username  varchar_ignorecase(50) not null,
//    authority varchar_ignorecase(50) not null,
//    constraint fk_authorities_users foreign key (username) references users (username)
//);
//create unique index ix_auth_username on authorities (username, authority);
create table groups
(
    id         bigint generated by default as identity (start with 0) primary key,
    group_name varchar_ignorecase(50) not null
);

create table group_authorities
(
    group_id  bigint      not null,
    authority varchar(50) not null,
    constraint fk_group_authorities_group foreign key (group_id) references groups (id)
);

create table group_members
(
    id       bigint generated by default as identity (start with 0) primary key,
    user_id  bigint      not null,
    group_id bigint      not null,
    constraint fk_group_members_user foreign key (user_id) references users (id),
    constraint fk_group_members_group foreign key (group_id) references groups (id)
);